name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - "config/cantor.keymap"
      - "keymap-drawer/keymap_drawer.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/cantor.keymap"
      config_path: "keymap-drawer/keymap_drawer.yaml"
      output_folder: "keymap-drawer"
      draw_args: "cantor:'--dts-layout boards/arm/toucan/toucan.dtsi --layout-name five_col_layout'"
      amend_commit: false
